### ISSUE TITLE
Environment Libero_Kitchen_Tabletop_Manipulation not found.

### ISSUE THREAD

**Issue by VictoriYang** [j96w/MimicPlay#2]
`Environment Libero_Kitchen_Tabletop_Manipulation not found. Make sure it is a registered environment among: Lift, Stack, NutAssembly, NutAssemblySingle, NutAssemblySquare, NutAssemblyRound, PickPlace, PickPlaceSingle, PickPlaceMilk, PickPlaceBread, PickPlaceCereal, PickPlaceCan, Door, Wipe, ToolHang, TwoArmLift, TwoArmPegInHole, TwoArmHandover, TwoArmTransport`

I am very interested in your work. I encountered an error while running run_trained_agent.py. What could be the possible reasons for this? Do you have any solutions for fixing the bug? Thanks!

**Comment by j96w** [comment]
Hey @VictoriYang , did you checkout the `v1.4.1_libero` branch when installing the robosuite? We add a line of [connection code](https://github.com/ARISE-Initiative/robosuite/commit/f564cbccbced51fb1f18c1f6538b3891777d849a) there for the Libero kitchen scene.

**Comment by VictoriYang** [comment]
This resolved the issue. Thank you for your guidance!
