### ISSUE TITLE
Hello, I would like to study the wrist-mounted camera part in STL format in your article. Can you provide me with a file?

### ISSUE THREAD

**Issue by lijinming2018** [j96w/MimicPlay#6]
Hello, I would like to study the wrist-mounted camera part in STL format in your article. Can you provide me with a file?

**Comment by j96w** [comment]
Sure, check out this https://www.tinkercad.com/things/kRbXQFFeN9m?sharecode=QiPlv6FnsmEPaNM9UbYYxZdrGiEMUExeJkz85LF4zq0
